#!/bin/sh

PROJECT=`php -r "echo dirname(dirname(dirname(realpath('$0'))));"`
STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep \\\\.php`

# Determine if a file list is passed
if [ "$#" -eq 1 ]
then
    oIFS=$IFS
    IFS='
    '
    SFILES="$1"
    IFS=$oIFS
fi
SFILES=${SFILES:-$STAGED_FILES_CMD}

echo "Checking PHP Lint..."
for FILE in $SFILES
do
    php -l -d display_errors=0 $PROJECT/$FILE
    if [ $? != 0 ]
    then
        echo "Fix the error before commit."
        exit 1
    fi
    FILES="$FILES $PROJECT/$FILE"
done

if [ "$FILES" != "" ]
then
    echo ""
    echo "Running Code Beautifier..."
    ./vendor/bin/phpcbf --standard=./contrib/phpcs/teamcontrib.xml --encoding=utf-8 -n -p $FILES
    git add $FILES

    echo ""
    echo "Running Code Sniffer..."
    ./vendor/bin/phpcs --standard=./contrib/phpcs/teamcontrib.xml --encoding=utf-8 -n -p $FILES
    if [ $? != 0 ]
    then
        echo "Please, fix these error(s) before commit."
        exit 1
    fi

    echo ""
    echo "Running PHP Mess Detector..."
    for FILE in $SFILES
    do
        ./vendor/bin/phpmd $PROJECT/$FILE text ./contrib/phpmd/teamcontrib.xml
        if [ $? != 0 ]
        then
            echo "Please verify this warnings to avoid creating messed up code! :)"
        fi
    done
fi

exit $?
